### ISSUE TITLE
SAUG: jwsacruncher log

### ISSUE THREAD

**Issue by Luis-Sanguiao** [jdemetra/jwsacruncher#16]
We have observed that, when there is something wrong with the workspace files, the output messages from the cruncher are not very helpful to determine where the error is.

This kind of information would be especially handy to debug our code when we modify workspace from an application before launching the cruncher. Therefore, some consistency checks on the workspace files and more verbosity in the outputs of the cruncher would be useful.

We propose that the cruncher writes a log file reporting these consistency checks on the workspace files. This log file would check exclusively workspace consistency, being unrelated to seasonal adjustment process itself.

**Comment by charphi** [comment]
Partialy done in #27

**Comment by charphi** [comment]
Checking workspace consistency is out of scope for jwsacruncher.
Fortunatly, this operation is already available in another tool called [jdemetra-cli](https://github.com/nbbrd/jdemetra-cli)

The specific documentation is available at https://github.com/nbbrd/jdemetra-cli/wiki/cmd_workspace
Here is an example: `dem workspace --check my_workspace.xml`
