### ISSUE TITLE
default parameters file

### ISSUE THREAD

**Issue by petterijuvonen** [jdemetra/jwsacruncher#17]
Hi!
For some reason jwsacruncher doesn't create the default parameter file when it that left unspecified. What could be the reason for this? Due to this I haven't been able to create any acceptable parameter file.

Petteri

**Comment by charphi** [comment]
The default parameter file should be created in the **working directory** when you launch the command line without parameters. You might not look at the right directory if you have created a shortcut.

**Comment by petterijuvonen** [comment]
Working directory is the one where the work space file exists? Have checked that and Output and SAPprocessing folders (and in fact whole computer for .params files).

When I only type jwsacruncher  (without defining the workspace file) I get :
Failed to create params file: null
Should it create a parameters file also in this case?

**Comment by charphi** [comment]
The working directory is the directory where you launch the application.
It is not the workspace directory.

I've just tested [the latest version of the jwsacruncher](https://github.com/jdemetra/jwsacruncher/releases) and it works as expected.

Could you try this:
1. open a command prompt
2. go to the directory where jwsacruncher is installed
3. run jwsacruncher without parameter

You should now see a new file called `wsacuncher.params`

**Comment by petterijuvonen** [comment]
Thanks, I tried this:
went to folder
C:\Program Files\jwsacruncher-2.2.0\jdemetra-cli-2.2.0\bin>
and typed
jwsacruncher
what I get is:
Failed to create params file: null

**Comment by petterijuvonen** [comment]
and it doesn't create the params file.

**Comment by charphi** [comment]
Do you have the permission to write in the current working directory?
What version of Java are you using? (`java -version`)

**Comment by petterijuvonen** [comment]
Thanks a lot! It was about the permission to write.
