### ISSUE TITLE
Quality Indicator

### ISSUE THREAD

**Issue by cagankaya** [jdemetra/jwsacruncher#19]
Hi There,

In previous versions (2.1.0), we got quality feedbacks (good,bad,severe etc.) as a column (quality) in demetra_m.csv. But in 2.2.0 version this column has been removed. Is there any chance to restore it.

Cagan
TurkSTAT

**Comment by palatej** [comment]
Hi, Cagan

The quality indicator is well generated by the cruncher-2.2.0.  Don't forget to specify the "diagnostics.quality" key in your spec file. 
To be noted that a new cruncher (2.2.1), which fixes some minor problems,  will be soon available.
