### ISSUE TITLE
 `jwsacruncher-2.2.5-bin.zip` missing in latest release

### ISSUE THREAD

**Issue by TanguyBarthelemy** [jdemetra/jwsacruncher#265]
In comparison with the 2.2.4 release, the files:

- [ ] `checksums_sha256.txt.asc`
- [ ] `jwsacruncher-2.2.4-bin.zip`
- [ ] `jwsacruncher-2.2.4-bin.zip.asc`
- [ ] `jwsacruncher-2.2.4-bin.zip.sha256`

are missing in the latest release (2.2.5).

Is is intended?

Thank you

**Comment by charphi** [comment]
It was not intended; the release failed somehow...

**Comment by charphi** [comment]
I've just added the missing binary in the release page.

**Comment by TanguyBarthelemy** [comment]
Thank you
