### ISSUE TITLE
jwsacruncher and mac os?

### ISSUE THREAD

**Issue by AQLT** [jdemetra/jwsacruncher#34]
Hi,
I was wondering if the jwsacruncher can be used in mac os or if it is only compatible with Windows? Using the same syntax that in a Windows I have an error  `jwsacruncher: command not found`.
Thanks

**Comment by charphi** [comment]
I should work by calling the script `/bin/jwsacruncher`.
Java 8 needs to be available on the command line and the script should be executable.

**Comment by AQLT** [comment]
Ok Thanks. 
Indeed it works! I was doing it wrongly: if you change the current directory to the bin directory, in mac you have to use `./jwsacruncher` and not `jwsacruncher` like in windows.
