### ISSUE TITLE
Rename variables

### ISSUE THREAD

**Issue by maria-novas** [jdemetra/jwsacruncher#6]
We have tested again the cruncher output, including User defined variables, with the new release of the cruncher (jwsacruncher-2.2.0-RC3). When we create new variables and rename them to include our own calendar regressors, it doesn’t work properly. It seems that it can’t find the variables correctly, when the name is not the default name. You can see an example bellow:
![userdefinedvariables](https://user-images.githubusercontent.com/17139327/27482336-56b479dc-5821-11e7-8223-bf68be14c2c5.jpg)
![demetra_m](https://user-images.githubusercontent.com/17139327/27482468-e04b21e6-5821-11e7-8b2d-195db74750a1.jpg)

**Comment by palatej** [comment]
OK. 
Thanks. I correct it for the official release.

Jean

**Comment by palatej** [comment]
see #7
