### ISSUE TITLE
Cruncher doesn't refresh  new data calendar regressors

### ISSUE THREAD

**Issue by maria-novas** [jdemetra/jwsacruncher#9]
When we introduce new data in the calendar regressors input file (Excel), the cruncher doesn’t refresh the xml files in the folder variables with the new data introduced, so the cruncher doesn’t run correctly. This also happens in the GUI. 
![jd_error](https://user-images.githubusercontent.com/17139327/30688509-adabbd5c-9ebe-11e7-8fad-4580ed9499a1.png)
Thanks in advance

**Comment by palatej** [comment]
Corrected in #10 
There is now a new parameter in the config file: "refreshall" (=true by default). The external (dynamic) variables will be refreshed before processing (except if refreshall=false).
